apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
  namespace: ms
type: Opaque
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9hcnBpdGFncjAxMjM6cTBvQ2RKdGp2cnUwSDhrOUBhcnBpdGNsdXN0ZXIwLmttbGZ0bHkubW9uZ29kYi5uZXQvCg==
